{
    "openapi": "3.0.0",
    "info": {
        "title": "Your API Title",
        "description": "Your API Description",
        "version": "1.0.0"
    },
    "security": [
        {
            "BearerAuth": []
        }
    ],
    "components": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "consumes": ["application/json"],
    "paths": {
        "/api/search": {
            "post": {
                "summary": "Effectuer une recherche",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des recherches"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/logout": {
            "get": {
                "summary": "deconnexion",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de compte"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/refresh": {
            "get": {
                "summary": "Rafraichir le token",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de compte"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/users/": {
            "put": {
                "summary": "Modification de compte",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de compte"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "user",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    },
                                    "prenom": {
                                        "type": "string"
                                    },
                                    "adresse": {
                                        "type": "string"
                                    },
                                    "telephone": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "password_confirmation": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "magid",
                                "prenom": "testabdoul",
                                "adresse": "dakar",
                                "telephone": "77855224",
                                "email": "emailtest1@gmail.com",
                                "password": "Password1@",
                                "password_confirmation": "Password1@"
                            }
                        }
                    }
                }
            },
            "api/users/": {
                "delete": {
                    "summary": "supprimé",
                    "description": "",
                    "responses": {
                        "204": {
                            "description": "Deleted successfully",
                            "content": {
                                "application/json": {
                                    "schema": {},
                                    "example": ""
                                }
                            }
                        }
                    },
                    "tags": ["Gestion des utilisateurs"],
                    "parameters": [
                        {
                            "in": "path",
                            "name": "user",
                            "type": "string"
                        },
                        {
                            "in": "header",
                            "name": "User-Agent",
                            "type": "string"
                        }
                    ]
                }
            }
        },
        "/api/updateadmin": {
            "patch": {
                "summary": "Modification de compte admin",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de compte"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "adminSystem",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    },
                                    "prenom": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "password_confirmation": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "testmagid",
                                "prenom": "testabdoul",
                                "password": "Password1@",
                                "password_confirmation": "Password1@"
                            }
                        }
                    }
                }
            }
        },
        "/api/profile": {
            "get": {
                "summary": "afficher l'utilisateur connecté ",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de compte"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/users": {
            "post": {
                "summary": "Creation d'un admin reseau",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des utilisateurs"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    },
                                    "prenom": {
                                        "type": "string"
                                    },
                                    "adresse": {
                                        "type": "string"
                                    },
                                    "telephone": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "reseau_id": "integer",
                                    "role_id": "integer",
                                    "password": {
                                        "type": "string"
                                    },
                                    "password_confirmation": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "magid",
                                "prenom": "abdoul",
                                "adresse": "dakar",
                                "telephone": "77855224",
                                "email": "email@gmail.com",
                                "reseau_id": 2,
                                "role_id": 3,
                                "password": "password",
                                "password_confirmation": "password"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/etat": {
            "get": {
                "summary": "Bloquer ou debloquer  un utilisateur",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des utilisateurs"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/roles/restaure/": {
            "get": {
                "summary": "restaurer",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des roles"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "role",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/roles/2": {
            "delete": {
                "summary": "supprimé",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des roles"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "role",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "put": {
                "summary": "Modifier un role",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des roles"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "role",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "modification"
                            }
                        }
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "summary": "Lister les roles",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des roles"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "post": {
                "summary": "Ajouter un role",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion des roles"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "adminreseau"
                            }
                        }
                    }
                }
            }
        },
        "/api/reseaux/restaurer/": {
            "get": {
                "summary": "restaurer un reseau",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "reseau",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/reseaux/": {
            "delete": {
                "summary": "Supprimer un reseau",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "reseau",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "get": {
                "summary": "Afficher un reseau",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "reseau",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/reseaux": {
            "get": {
                "summary": "Lister les reseaux",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "post": {
                "summary": "Ajouter un reseau",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "aftu"
                            }
                        }
                    }
                }
            }
        },
        "/api/reseaux/2": {
            "patch": {
                "summary": "Modifier un reseau",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de reseaux"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "nom": "aftusenegal"
                            }
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "summary": "connexion",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": ["Gestion de l'authentification"],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "guillaume.lemonnier@example.com",
                                "password": "Password"
                            }
                        }
                    }
                }
            }
        }
    }
}
